version: 0.2

phases:
  install:
    commands:
      - echo "Installing unzip, curl, wget..."
      - apt-get update && apt-get install -y unzip curl wget

      - echo "Downloading Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -O terraform.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - chmod +x /usr/local/bin/terraform
      - terraform --version

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

      - echo "Validating Terraform..."
      - terraform validate

      - echo "Planning Terraform..."
      - terraform plan -var="region=$AWS_REGION"

  post_build:
    commands:
      - echo "Build complete."
