version: 0.2

phases:
  install:
    runtime-versions:
      python: python3.8
      # Add other runtime versions as needed
    # Install Terraform
    # You can use `aws codebuild build-environment` to get the current environment.
    # If no environment variables are specified, you can specify a version number
    # For example, runtime-versions: terraform: 1.1.0
    commands:
      - echo "Installing Terraform"
      - echo "Fetching Terraform from AWS"
      - curl -o terraform https://github.com/hashicorp/terraform/releases/download/v0.14.9/terraform_0.14.9_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/terraform
      - chmod +x /usr/local/bin/terraform
  build:
    commands:
      - echo "Building infrastructure..."
      - echo "Initializing Terraform"
      - terraform init
      - echo "Planning changes"
      - terraform plan
      - echo "Applying changes"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Deployment complete!"
      - echo "Cleaning up"
