version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - echo "Build complete"
  post_build:
    commands:
      - echo "Triggering backend deployment..."
      # Add SSM or SCP command here
artifacts:
  files: []
