version: 0.2
phases:
  install:
    runtime-versions:
      docker: "18.9"
      python: "python3.8"  # Or your preferred Python version
    commands:
      - yum update -y
      - yum install -y wget unzip
      - wget https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip
      - unzip terraform_0.14.10_linux_amd64.zip
      - sudo mv terraform /bin/terraform
      - chmod +x /bin/terraform
      - terraform --version # Verify Terraform installation
  build:
    commands:
      - terraform -v  # Verify Terraform version
      - terraform init
      - terraform validate
      - terraform plan -var="region=$AWS_REGION"  #  Use $AWS_REGION if region is an environment variable
  post_build:
    commands:
      - echo "Build complete."
      -
