version: 0.2

phases:
  install:
    commands:
      - echo "Installing unzip and curl if missing..."
      - if command -v yum >/dev/null; then yum install -y unzip curl; fi
      - if command -v apt-get >/dev/null; then apt-get update && apt-get install -y unzip curl; fi

      - echo "Downloading Terraform..."
      - curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip

      - echo "Unzipping Terraform..."
      - unzip -o terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo "Initializing Terraform"
      - cd terraform
      - terraform init

      - echo "Planning changes"
      - terraform plan -out=tfplan

      - echo "Applying changes"
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Deployment complete!"
