version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing unzip...
      - yum install -y unzip
      - echo Downloading Terraform...
      - curl -fSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - echo Checking downloaded file...
      - ls -lh terraform.zip
      - unzip terraform.zip || (echo "Unzip failed. Download may have failed." && exit 1)
      - mv terraform /usr/local/bin/
      - terraform version
