version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing unzip..."
      - yum install -y unzip
      - echo "Downloading Terraform..."
      - curl -fSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - echo "Unzipping..."
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Changing directory to terraform/"
      - cd terraform
      - terraform init

  build:
    commands:
      - echo "Running terraform plan/apply"
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
