version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
  build:
    commands:
      - cd infra
      - terraform init
      - terraform apply -auto-approve
