version: 0.2

phases:
  install:
    commands:
      - echo "Detected Ubuntu environment. Updating apt..."
      - apt-get update -y
      - apt-get install -y unzip curl
      - echo "Downloading Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip -o terraform.zip
      - unzip -o terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

artifacts:
  files: []
